### ISSUE TITLE
Checkpoint 2 Review

### ISSUE THREAD

**Issue by pawaitemadisoncollege** [GuruKatuwal/BillingSystem#10]
@GuruKatuwal 

These items are required to be completed for checkpoint 2 completion: 

- [ ] Replace all printlns and printstacktraces with logging statements. Example: https://github.com/GuruKatuwal/BillingSystem/blob/79455e6d311c8be65a1ea492a919fee8d40b0eb7/src/main/java/BillingSystem/persistence/Database.java#L33-L40 and https://github.com/GuruKatuwal/BillingSystem/blob/79455e6d311c8be65a1ea492a919fee8d40b0eb7/src/main/java/BillingSystem/persistence/Database.java#L73
- [ ] Can you point me to your ERD (database design diagrame) on GitHub?
- [ ] Some unit tests are commented out?  For checkpoint 2, can you share a screenshot showing that unit tests are passing for at least one Dao?

This can be done after checkpoint 2:

- [ ] After implementing the GenericDao, you should remove the entity-specific daos.  Be sure to leave the unit tests though - just covert them over to use the GenericDao.

**Comment by GuruKatuwal** [comment]
@pawaitemadisoncollege  I fixed my database link for DatabaseDiagram and take out the System.out.println.

**Comment by pawaitemadisoncollege** [comment]
Thanks for uploading the ERD. Just a couple things:

- [x] You have a user entity and role entity that seem to correspond to a user table and role table, but I don't really see these same structures in the database design. More questions about this follow... 
- [x] It seems like the User table in the ERD holds the role/s for a customer or employee? If that is correct, would this be better name role?
- [x] Customer and Employee seem like they could be rolled into a single User table, and then the Role table could be used to indicate whether a user is a Customer, an Employee, or even both (a user could have more than one role).

**Comment by GuruKatuwal** [comment]
I have upgraded my ERD.  originally I only have employee and customer later we did an authentication exercise, that's where I messed up. now I only have one user table which has role and description where I can specify  for employee or customer.

**Comment by pawaitemadisoncollege** [comment]
Sounds good! Thanks for the update!
