### ISSUE TITLE
time log formatting does not display as a table

### ISSUE THREAD

**Issue by pawaitemadisoncollege** [GuruKatuwal/BillingSystem#3]
![Screen Shot 2020-09-16 at 2 15 58 PM (2)](https://user-images.githubusercontent.com/13874466/93382103-3e3fc100-f827-11ea-8ea3-d3410ab7a99f.png)

It should show up as table instead - I think you are missing some "pipes": |

**Comment by GuruKatuwal** [comment]
Fixed!
