### ISSUE TITLE
Checkpoint 1 - Review

### ISSUE THREAD

**Issue by pawaitemadisoncollege** [GuruKatuwal/BillingSystem#4]
Just a few things to touch up for the first checkpoint:

- [x] See the other issue on your repository regarding time log formatting. 
- [x] Be sure you have screens showing all aspects of all user stories. Example - is there a screen for the admin deleting a user?
- [x] Improve formatting of UserStories.md so that the hashes are not displayed in github - I think adding a space between the hashes and the text will fix the problem. See below.
<img width="1680" alt="Screen Shot 2020-09-25 at 7 14 51 PM" src="https://user-images.githubusercontent.com/13874466/94325405-d0507380-ff63-11ea-8f6c-48acf27a4534.png">

**Comment by GuruKatuwal** [comment]
Done
