### ISSUE TITLE
 Authentication Exercise is done!

### ISSUE THREAD

**Issue by GuruKatuwal** [GuruKatuwal/BillingSystem#8]
@pawaitemadisoncollege , I am done with Authentication Exercise.

**Comment by pawaitemadisoncollege** [comment]
This is a good start on authentication @GuruKatuwal!

Keep in mind that you will want to restrict access not only to the jsps, but any related resources, such as the servlet, to prevent that savvy user from bypassing the jsps. 

As you add more functionality to your project, be sure to add security along the way!
